<a href="https://colab.research.google.com/github/Shamitha018/Numpy/blob/main/O_21_11_2025_Numpy_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
np.__version__

'2.0.2'

In [4]:
a = [10, 20, 30, 40]
b= [100, 200, 300, 400]
c=[]
for i,j in zip(a,b):
  c.append(i+j)
c

[110, 220, 330, 440]

In [5]:
l = [i+j for i,j in zip(a,b)]
l

[110, 220, 330, 440]

creating arrays using numpy

In [7]:
ar1 = np.array(a)
ar2 = np.array(b)
ar1, ar2

(array([10, 20, 30, 40]), array([100, 200, 300, 400]))

In [8]:
ar1+ar2

array([110, 220, 330, 440])

In [9]:
ar1-ar2

array([ -90, -180, -270, -360])

In [10]:
ar1*ar2


array([ 1000,  4000,  9000, 16000])

In [11]:
ar1/ar2

array([0.1, 0.1, 0.1, 0.1])

In [12]:
ar1%ar2

array([10, 20, 30, 40])

In [5]:
import time
start = time.time()
l1 = list(range(1,1000000))
l2 = list(range(1,1000000))
l3=[i*j for i,j in zip(l1,l2)]
end = time.time()
print(f'time taken to multiply two lists is {end-start} seconds')

time taken to multiply two lists is 3.520447254180908 seconds


In [6]:
import time
import numpy as np
start = time.time()
arr1 = np.arange(1,1000000)
arr2 = np.arange(1,1000000)
arr1 * arr2
end = time.time()
print(end-start)

0.01278829574584961


dimensions in numpy

In [7]:
list1 = [1,2,3,4]
oa1 = np.array(list1)
oa1

array([1, 2, 3, 4])

In [8]:
oa1.ndim

1

In [9]:
oa1.shape

(4,)

In [10]:
oa1.size

4

2d

In [11]:
l1 = [10,20,90]
l2 = [0,9,8]
np.array(l1,l2)

TypeError: Field elements must be 2- or 3-tuples, got '0'

In [13]:
new = np.array([l1,l2])
new

array([[10, 20, 90],
       [ 0,  9,  8]])

In [14]:
new.ndim

2

In [15]:
new.shape

(2, 3)

In [16]:
new.size

6

3d

In [24]:
l3 = [9,8,7]
d3 = np.array([[l1,l2,l3]])
d3

array([[[10, 20, 90],
        [ 0,  9,  8],
        [ 9,  8,  7]]])

In [25]:
d3.ndim

3

In [26]:
d3.shape

(1, 3, 3)

In [27]:
l = [1,2,3]
lz = [1,1,1]
nl = [l,lz]
n = np.array(nl)

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
l = [2,2]
l1 = [l,l]
l2= []

In [28]:
#2,4
l = [1,2,3,4]
l1 = [l,l]
np.array(l1).shape

(2, 4)

In [30]:
#3,3,4
l = [0,0,0,0]
l1 = [l,l,l]
l2= [l1,l1,l1]
np.array(l2).shape

(3, 3, 4)

In [34]:
#4,3,2,2
k = [1,2]
l =[k,k]
l1 = [l,l,l]
l2= [l1,l1,l1,l1]
np.array(l2).shape

(4, 3, 2, 2)

In [32]:
#5,4,3,2,1
l=[1]
l1 = [0]
l2 = [l1,l1]
l3 = [l2,l2,l2]
l4 = [l3,l3,l3,l3]
l5 = [l4,l4,l4,l4,l4]
np.array(l5).shape

(5, 4, 3, 2, 1)

In [46]:
#4,3,4,4
k = [1,2,3,4]
j = ['well', 'being', 'is', 'important']
l =[k,j]
l3 = [j,k]
l1 = [l,l3,l]
l2= [l1,l1,l1,l1]
np.array(l2).shape

(4, 3, 2, 4)