<a href="https://colab.research.google.com/github/Shamitha018/Numpy/blob/main/O_24_111_2025_Numpy_session_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.random.randint(1,100,size=10)

array([ 1, 14,  7, 32, 90,  4, 97, 85, 55, 57])

In [ ]:
np.random.randint(1,100,size=(2,2))

array([[10, 28],
       [79, 71]])

In [ ]:
np.random.random()

0.1178486195833508

In [ ]:
np.random.random(size=None) #default parameter, random generates values with default upper limit and lower limit as 1,0

0.6996357079296764

In [ ]:
np.random.random([2,5])


array([[0.02852557, 0.56750789, 0.43433786, 0.99782058, 0.89639089],
       [0.526177  , 0.62231467, 0.74663926, 0.08223876, 0.0060738 ]])

In [ ]:
np.random.rand()

0.028192426421140393

In [ ]:
np.random.rand(2,3)

array([[0.35863366, 0.78468099, 0.44688295],
       [0.7666101 , 0.73796728, 0.34123798]])

In [ ]:
np.random.randn()

-0.3843298982431218

In [ ]:
np.random.randn(2,3) #standard normal distribution values

array([[-0.33094345,  1.00458209,  1.87411345],
       [ 0.08895671, -0.47367423, -2.09533889]])

In [ ]:
np.random.choice((2,10), p=[1,0])

np.int64(2)

In [ ]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((3,3), dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.zeros((3,3), dtype=np.float64)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(0)

array([], dtype=float64)

In [ ]:
np.ones(1)

array([1.])

In [ ]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones_like([0,0,0,10]) #a not shape, takes output same as given array shape

array([1, 1, 1, 1])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.full((3,4),fill_value=4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])