<a href="https://colab.research.google.com/github/Shamitha018/Numpy/blob/main/O_24_111_2025_Numpy_session_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#min max mean median mode using numpy methods
import numpy as np
arr = np.random.randint(1,100, size=10)
print(arr)

[49 47 20 34 97 62 93 68 62 38]


In [ ]:
arr.min()

np.int64(20)

In [ ]:
arr.max()

np.int64(97)

In [ ]:
arr.mean()

np.float64(57.0)

In [ ]:
arr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

variance, standard deviation, cov, correlation, z score, min max scalar, distances

In [ ]:
arr.std()

np.float64(23.430749027719962)

for a list of values

In [ ]:
l= [8,9,7,6,5,4]
np.min(l)

np.int64(4)

In [ ]:
np.max(l)

np.int64(9)

In [ ]:
np.mean(l)

np.float64(6.5)

In [ ]:
np.median(l)

np.float64(6.5)

In [ ]:
np.modf(l)

(array([0., 0., 0., 0., 0., 0.]), array([8., 9., 7., 6., 5., 4.]))

In [ ]:
np.std(l)

np.float64(1.707825127659933)

In [ ]:
np.var(l)

np.float64(2.9166666666666665)

In [ ]:
np.cov(l)

array(3.5)

In [ ]:
np.correlate(l, l)

array([271])

In [ ]:
np.min_scalar_type(l)

dtype('int64')