<a href="https://colab.research.google.com/github/Shamitha018/Numpy/blob/main/O_25_11_2025_Numpy_session_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
l=[10,20,30,40,50,60,70,80,90,100]
arr = np.array(l)

In [4]:
np.min(arr)

np.int64(10)

In [5]:
np.max(arr)

np.int64(100)

In [10]:
count = np.count_nonzero(l)
count

10

In [11]:
np.mean(arr)

np.float64(55.0)

In [13]:
sum = np.sum(arr)
mean = sum/count
mean

np.float64(55.0)

In [2]:
np.median(arr)

np.float64(55.0)

In [3]:
np.var(arr)

np.float64(825.0)

VARIANCE STEP BY STEP WITHOUT METHOD

In [9]:
#step 1: xi means array
arr-np.mean(arr, dtype=int)

array([-45, -35, -25, -15,  -5,   5,  15,  25,  35,  45])

In [15]:
#step2: square it
square =np.square(arr-np.mean(arr))
square

array([2025., 1225.,  625.,  225.,   25.,   25.,  225.,  625., 1225.,
       2025.])

In [16]:
#step 3: sum of squared values
np.sum(square)

np.float64(8250.0)

In [18]:
#step 4: divide the sum by count of observations
var =np.sum(square)/count
var

np.float64(825.0)

In [26]:
l = [10,20,30,40,50,60,70,80,90,100]
array=np.array(l)
np.sqrt(np.sum(np.square(array-np.mean(array)))/np.count_nonzero(array))

np.float64(28.722813232690143)

In [33]:
np.std(array)

np.float64(28.722813232690143)

covariance = sum ( xi-xbar)(yi - ybar) / N

In [44]:
x=np.arange(1,11)
y=np.arange(100,110)
xbar = np.sum(x)/len(x)
ybar=np.sum(y)/len(y)
np.sum((x-xbar)*(y-ybar))/len(y)

np.float64(8.25)

In [45]:
np.cov(x,y)

array([[9.16666667, 9.16666667],
       [9.16666667, 9.16666667]])

correlation

In [46]:
std_x=np.sqrt(np.sum(np.square(x-xbar)) / np.count_nonzero(x))
std_y=np.sqrt(np.sum(np.square(y-ybar)) / np.count_nonzero(y))
cor = (np.sum((x-xbar)*(y-ybar))/np.count_nonzero(y)) / (std_x *std_y)
cor

np.float64(1.0)

In [50]:
#Euclidean distance
x=(10,20)
y=(5,6)
arr1 = np.array(x)
arr2=np.array(y)
ed= np.sqrt(np.sum(np.square(arr1-arr2)))
ed

np.float64(14.866068747318506)

In [51]:
from numpy.linalg import norm
norm(arr1-arr2)

np.float64(14.866068747318506)

cosine similarity = dot(a,b)/norm(a) * norm(b)

In [55]:
x = [1,2,3]
y=[4,5,6]
arr1 = np.array(x)
arr2= np.array(y)
cosine= np.dot(arr1,arr2)/(norm(arr1) * norm(arr2))
cosine

np.float64(0.9746318461970762)